### ISSUE TITLE
DO NOT WASTE YOUR TIME

### ISSUE THREAD

**Issue by oisact** [ifew/php-prevent-video-download#3]
This is incomplete and non-functional code. It will not work. For example, it `fopen` a file, but then never uses the file handle `$fp` for reading. Instead it calls `readfile` which just dumps the entire file out.

Also, what is this??
```
if (isset($_SERVER['HTTP_RANGE'])) {
    if (isset($_SERVER['HTTP_RANGE'])) {
```

It appears this is a hacked up version of https://gist.github.com/codler/3906826 that doesn't actually function.

**Comment by ifew** [comment]
Thank you, I follow this code from them, and I am sorry for not work. and I will fix it
